spring:
  application:
    name: chagok
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/parkinghub
    username: valetparker
    password: valetparker

server:
  servlet:
    encoding:
      force: true

kakaopay:
  secretKey:
  cid: pay